### ISSUE TITLE
This code use test accuracy to select model

### ISSUE THREAD

**Issue by LingxiaoShawn** [HongyangGao/gunet#16]
Hi Hongyang,
It's nice structured code, but it seems you are using test accuracy to do model selection, am I correct?

**Comment by HongyangGao** [comment]
Yes. We follow the common practice in the community and use 10-fold cross-validation.

**Comment by pursueorigin** [comment]
Hi,

I have a question about selecting models. 
In DGCNN https://github.com/muhanzhang/pytorch_DGCNN/issues/19, the author uses the accuracy of the test set at the last iteration. 
In this paper, the best accuracy of the test set is used. 

Which one should be used in your opinion? In addition, how did you handle DGCNN in Table 4 of this paper?  Thanks.
