### ISSUE TITLE
针对大图做节点分类的问题

### ISSUE THREAD

**Issue by tanjia123456** [HongyangGao/gunet#26]
你好，我准备使用Graph u-net来做节点分类，总共58个图，每个图的邻接矩阵是固定的，（10242*10242），每个节点有10个特征（10242，10），一共30个类别，我使用的池化率是[0.9, 0.8, 0.7]，

大图处理起来太复杂了，每个epoch要做很多次gcn，谱域又比较耗时，请问有啥处理办法吗？感觉这个代码不太适合大图

**Comment by dream-00** [comment]
请问针对这个问题你有什么好的解决办法了吗？
