### ISSUE TITLE
Adjacency Matrix Augmentation

### ISSUE THREAD

**Issue by YannDubs** [HongyangGao/gunet#7]
Hi I cannot seem to find where you augment the adjacency matrix. Could you please point me to the line in which you do it ? I wanted to check I fou you do A^2 or (A+I)^2

**Comment by YannDubs** [comment]
Furthermore, from the paper it is not clear in the unpooling if you reuse the corresponding augmented adjacency matrix or the non augmented version. Could you give more details about how you use graph augmentation (or point to some code) ? 
Thanks!

**Comment by Yfhu1103** [comment]
> Hi I cannot seem to find where you augment the adjacency matrix. Could you please point me to the line in which you do it ? I wanted to check I fou you do A^2 or (A+I)^2

I cannot see the augment too, if you have any idea, pls let me know, thanks!
